### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Zorklis** [RPCSX/rpcsx#18]
Since someone will ask eventually, might as well make it clear.
Why just Linux

**Comment by IceDBorn** [comment]
Chad move

**Comment by michaeljhkim** [comment]
> Since someone will ask eventually, might as well make it clear. Why just Linux

Linux is significantly easier to develop on. I am not personally working on the project, but I know that linux can compile things much faster, as well as having better tools readily available. 

Join us. Become one of us. It is better than being under the heavy iron boots of windows.

**Comment by KingKrouch** [comment]
> Linux is significantly easier to develop on. I am not personally working on the project, but I know that linux can compile things much faster, as well as having better tools readily available.

Might be possible to set up MinGW (via MSys2 or through a bog-standard Distro in Linux or WSL) as a toolchain. I've had luck compiling Windows applications through Fedora without relying on Visual Studio for example.

**Comment by IceDBorn** [comment]
> Might be possible to set up MinGW (via MSys2 or through a bog-standard Distro in Linux or WSL) as a toolchain. I've had luck compiling Windows applications through Fedora without relying on Visual Studio for example.
Will WSL work when the project is more complex though? Just asking, I don't know the performance it can achieve on GUI apps.

**Comment by Sintaxa** [comment]
Sucks that it's not for windows.

**Comment by RyzenDew** [comment]
> > Might be possible to set up MinGW (via MSys2 or through a bog-standard Distro in Linux or WSL) as a toolchain. I've had luck compiling Windows applications through Fedora without relying on Visual Studio for example.
> 
> Will WSL work when the project is more complex though? Just asking, I don't know the performance it can achieve on GUI apps.

WSL doesn't work 

Can I run emulator on Windows if it has WSL?

- No, you cannot. Because of limited GPU acceleration for applications that runs in WSL, no known way to run GPU emulator part on it

**Comment by Darkhost1999** [comment]
I think the idea was to have an open and locked issue explaining why windows support isn't happening yet from a developer who is working on rpcsx.
Not a bunch of comments from people but that was to be expected while awaiting an official response.
