### ISSUE TITLE
remove spirv-cross version check

### ISSUE THREAD

**Issue by Brutal-sam** [RPCSX/rpcsx#42]
compiling with the latest August 6th commits on ubuntu 22.04 succeeds but nothing works when running the emu, no games/samples run. turns out that's because of the spirv-cross version like DH suggested (even though that's the latest version available to install)
the solution is commenting out printSpirv's body at hw/amdgpu/device/src/device.cpp:1717 and 2 other lines 3393 and 3402 in the same file.
hope this gets fixed in a future commit and spirv-cross is ditched.

![invalid spirv](https://github.com/RPCSX/rpcsx/assets/94696121/7460a61e-b339-4b66-9b5c-8d66fb60afa3)

**Comment by DHrpcs3** [comment]
We have no checks for spirv-cross. Problem in the version that you have installed, it has no support of spirv 1.6. Ubuntu 23.10 might be supported with the first release, but ubuntu 22.04 uses outdated packages, we won't support it
