### ISSUE TITLE
RPCSX Sample or Game error

### ISSUE THREAD

**Issue by TheWizWikii** [RPCSX/rpcsx#63]
A few months ago, I was using the emulator without any issues. However, these days, I've re-downloaded, compiled, etc., but I'm encountering some errors that I'm not familiar with. I've attached some screenshots here, but I'm unable to launch any sample .elf or game with the decrypted eboot.ef. Any suggestions?

This happens during the attempt to run a sample or game using the command.
rm -f /dev/shm/rpcsx-* && ./rpcsx-os --mount ./system /system --mount ./app0 /app0 /app0/eboot.elf

![Captura desde 2024-01-14 18-52-55](https://github.com/RPCSX/rpcsx/assets/37479586/63e5d109-71bc-4b61-b760-2080503c4d05)
![Captura desde 2024-01-14 18-59-35](https://github.com/RPCSX/rpcsx/assets/37479586/8742fa43-7ef7-4b97-b3d3-cd2626d6ddd0)
![Captura desde 2024-01-14 19-00-09](https://github.com/RPCSX/rpcsx/assets/37479586/cabeb40d-badb-42dc-aceb-865430ce7d66)
![Captura desde 2024-01-14 19-00-29](https://github.com/RPCSX/rpcsx/assets/37479586/b11c5d2f-d2f2-4d29-a2d0-519ee4049bb7)
![Captura desde 2024-01-14 19-01-00](https://github.com/RPCSX/rpcsx/assets/37479586/36e46aa2-35be-4379-bcfb-f54b93b5a632)

**Comment by DHrpcs3** [comment]
Should be fixed already
