### ISSUE TITLE
(REQUEST) add aarch handles for linuwind

### ISSUE THREAD

**Issue by daviDarthemis** [RPCSX/rpcsx#88]
-- Using the multi-header code from /root/build/rpcsx/3rdparty/json/include/
CMake Error at /usr/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:233 (message):             Could NOT find libunwind (missing: libunwind_x86_64_LIBRARY) (found version
  "1.6.2")                                                                                                Call Stack (most recent call first):
  /usr/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:603 (_FPHSA_FAILURE_MESSAGE)            cmake/Findlibunwind.cmake:10 (find_package_handle_standard_args)
  rpcsx/CMakeLists.txt:1 (find_package)

**Comment by red-prig** [comment]
Why do you use aarch if the emulator only supports x86_64 ???

**Comment by DHrpcs3** [comment]
libunwind used for stack unwinding of guest thread, i.e. x86_64. No reason to try use libunwind for aarch64 instead
